import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1758873698326 implements MigrationInterface {
    name = 'InitialMigration1758873698326'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`sessions\` (\`id\` varchar(36) NOT NULL, \`user_id\` varchar(255) NOT NULL, \`token_hash\` varchar(255) NOT NULL, \`user_agent\` varchar(255) NULL, \`ip_address\` varchar(45) NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`last_used_at\` timestamp NOT NULL, \`expires_at\` timestamp NOT NULL, \`revoked_at\` timestamp NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_pii\` (\`user_id\` varchar(255) NOT NULL, \`cccd_cipher\` longblob NOT NULL, \`cccd_hash\` longblob NULL, \`address_line1\` varchar(255) NULL, \`address_line2\` varchar(255) NULL, \`ward\` varchar(255) NULL, \`district\` varchar(255) NULL, \`province\` varchar(255) NULL, \`postal_code\` varchar(255) NULL, \`country_code\` char(2) NOT NULL DEFAULT 'VN', \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_aba7f426e9bb429ff282f18d6c\` (\`cccd_hash\`), PRIMARY KEY (\`user_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`password_reset_tokens\` (\`id\` varchar(36) NOT NULL, \`user_id\` varchar(255) NOT NULL, \`token_hash\` varchar(255) NOT NULL, \`expires_at\` timestamp NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`consumed_at\` timestamp NULL, UNIQUE INDEX \`IDX_91185d86d5d7557b19abbb2868\` (\`token_hash\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`phone_verification_codes\` (\`id\` varchar(36) NOT NULL, \`user_id\` varchar(255) NOT NULL, \`phone_e164\` varchar(255) NOT NULL, \`code_hash\` varchar(255) NOT NULL, \`expires_at\` timestamp NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`consumed_at\` timestamp NULL, UNIQUE INDEX \`IDX_f0508fbd372dfe40db9160498f\` (\`code_hash\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`audit_log\` (\`id\` varchar(36) NOT NULL, \`user_id\` varchar(255) NULL, \`action\` varchar(255) NOT NULL, \`ip_address\` varchar(45) NULL, \`user_agent\` varchar(255) NULL, \`data\` json NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`virtual_transactions\` (\`id\` varchar(36) NOT NULL, \`portfolio_id\` varchar(255) NOT NULL, \`symbol_id\` bigint NOT NULL, \`symbol_code\` varchar(255) NOT NULL, \`transaction_type\` enum ('BUY', 'SELL') NOT NULL, \`quantity\` int NOT NULL, \`price_per_share\` bigint NOT NULL, \`total_amount\` bigint NOT NULL, \`fee\` bigint NOT NULL DEFAULT '0', \`tax\` bigint NOT NULL DEFAULT '0', \`net_amount\` bigint NOT NULL, \`status\` enum ('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED') NOT NULL DEFAULT 'PENDING', \`failure_reason\` text NULL, \`market_data\` json NULL, \`portfolio_balance_before\` bigint NOT NULL, \`portfolio_balance_after\` bigint NOT NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`executed_at\` timestamp NULL, INDEX \`IDX_02dbb30ab6376cd41e688dd7aa\` (\`symbol_code\`, \`created_at\`), INDEX \`IDX_6ad3ee8d7b3e38a44d297dd7d9\` (\`portfolio_id\`, \`created_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`symbols\` (\`id\` bigint NOT NULL, \`symbol\` varchar(255) NOT NULL, \`type\` varchar(255) NOT NULL, \`board\` varchar(255) NOT NULL, \`en_organ_name\` varchar(255) NULL, \`organ_short_name\` varchar(255) NULL, \`organ_name\` varchar(255) NULL, \`product_grp_id\` varchar(255) NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_8537c94ae17acdcbd2cc15c99a\` (\`symbol\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`virtual_holdings\` (\`id\` varchar(36) NOT NULL, \`portfolio_id\` varchar(255) NOT NULL, \`symbol_id\` bigint NOT NULL, \`symbol_code\` varchar(255) NOT NULL, \`quantity\` int NOT NULL, \`average_price\` bigint NOT NULL, \`total_cost\` bigint NOT NULL, \`current_price\` bigint NOT NULL DEFAULT '0', \`current_value\` bigint NOT NULL DEFAULT '0', \`unrealized_profit_loss\` bigint NOT NULL DEFAULT '0', \`profit_loss_percentage\` decimal(10,4) NOT NULL DEFAULT '0.0000', \`last_price_update\` timestamp NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`virtual_portfolios\` (\`id\` varchar(36) NOT NULL, \`user_id\` varchar(255) NOT NULL, \`cash_balance\` bigint NOT NULL DEFAULT '10000000000', \`total_asset_value\` bigint NOT NULL DEFAULT '10000000000', \`stock_value\` bigint NOT NULL DEFAULT '0', \`total_profit_loss\` bigint NOT NULL DEFAULT '0', \`profit_loss_percentage\` decimal(10,4) NOT NULL DEFAULT '0.0000', \`total_transactions\` int NOT NULL DEFAULT '0', \`successful_trades\` int NOT NULL DEFAULT '0', \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`subscription_packages\` (\`id\` varchar(36) NOT NULL, \`name\` varchar(255) NOT NULL, \`description\` text NULL, \`price\` decimal(10,2) NOT NULL, \`currency\` varchar(3) NOT NULL DEFAULT 'VND', \`duration_days\` int NOT NULL, \`is_active\` tinyint NOT NULL DEFAULT 1, \`features\` json NULL, \`max_virtual_portfolios\` int NULL, \`daily_api_limit\` int NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_4d8bf52f924d05dfcbc7355ae9\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_subscriptions\` (\`id\` varchar(36) NOT NULL, \`user_id\` varchar(255) NOT NULL, \`package_id\` varchar(255) NOT NULL, \`status\` enum ('active', 'expired', 'cancelled', 'suspended') NOT NULL DEFAULT 'active', \`starts_at\` timestamp NOT NULL, \`expires_at\` timestamp NOT NULL, \`auto_renew\` tinyint NOT NULL DEFAULT 0, \`price\` decimal(10,2) NULL, \`currency\` varchar(3) NULL, \`payment_reference\` varchar(255) NULL, \`cancelled_at\` timestamp NULL, \`cancellation_reason\` varchar(255) NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_409f50ec5f890102bbe16b02a9\` (\`expires_at\`), INDEX \`IDX_cf427b0b12e1b2ee93a64328e1\` (\`user_id\`, \`status\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` varchar(36) NOT NULL, \`email\` varchar(255) NOT NULL, \`password_hash\` varchar(255) NOT NULL, \`display_name\` varchar(255) NULL, \`full_name\` varchar(255) NULL, \`phone_e164\` varchar(255) NULL, \`phone_verified_at\` timestamp NULL, \`role\` varchar(255) NOT NULL DEFAULT 'member', \`is_active\` tinyint NOT NULL DEFAULT 1, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), UNIQUE INDEX \`IDX_4263ae397e23dff35b72ddfd34\` (\`phone_e164\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`watchlists\` (\`id\` varchar(36) NOT NULL, \`user_id\` varchar(255) NOT NULL, \`symbol_id\` bigint NOT NULL, \`custom_name\` varchar(255) NULL, \`notes\` text NULL, \`alert_price_high\` decimal(15,2) NULL, \`alert_price_low\` decimal(15,2) NULL, \`is_alert_enabled\` tinyint NOT NULL DEFAULT 0, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_a44cd15737dd16fff31cdc44eb\` (\`symbol_id\`), INDEX \`IDX_3e8bccad3dcd75fa977892c54b\` (\`user_id\`), UNIQUE INDEX \`IDX_97e54cee8cbc1ec75de877e809\` (\`user_id\`, \`symbol_id\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`virtual_leaderboard\` (\`id\` varchar(36) NOT NULL, \`user_id\` varchar(255) NOT NULL, \`portfolio_id\` varchar(255) NOT NULL, \`username\` varchar(255) NOT NULL, \`total_asset_value\` bigint NOT NULL, \`initial_balance\` bigint NOT NULL DEFAULT '10000000000', \`total_profit_loss\` bigint NOT NULL, \`profit_loss_percentage\` decimal(5,2) NOT NULL, \`total_transactions\` int NOT NULL, \`successful_trades\` int NOT NULL, \`win_rate\` decimal(5,2) NOT NULL DEFAULT '0.00', \`rank_by_value\` int NULL, \`rank_by_percentage\` int NULL, \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), INDEX \`IDX_d54ddd7d6b0ec56ffac255b177\` (\`profit_loss_percentage\`, \`updated_at\`), INDEX \`IDX_80c717c53b6831e5f4fd84e840\` (\`total_asset_value\`, \`updated_at\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`sessions\` ADD CONSTRAINT \`FK_085d540d9f418cfbdc7bd55bb19\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_pii\` ADD CONSTRAINT \`FK_e85a7597ec6d0d467e7a469c556\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`password_reset_tokens\` ADD CONSTRAINT \`FK_52ac39dd8a28730c63aeb428c9c\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`phone_verification_codes\` ADD CONSTRAINT \`FK_0dbeb26c5cef6479baec0d78db4\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`audit_log\` ADD CONSTRAINT \`FK_cb11bd5b662431ea0ac455a27d7\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`virtual_transactions\` ADD CONSTRAINT \`FK_aab9123451c6a75958b42da41b7\` FOREIGN KEY (\`portfolio_id\`) REFERENCES \`virtual_portfolios\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`virtual_transactions\` ADD CONSTRAINT \`FK_553de9662a6a5e3dc999a1748e6\` FOREIGN KEY (\`symbol_id\`) REFERENCES \`symbols\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`virtual_holdings\` ADD CONSTRAINT \`FK_ff87ac76bc21a58c927d634a08d\` FOREIGN KEY (\`portfolio_id\`) REFERENCES \`virtual_portfolios\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`virtual_holdings\` ADD CONSTRAINT \`FK_10e60e3392d30dec8df94b21ece\` FOREIGN KEY (\`symbol_id\`) REFERENCES \`symbols\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`virtual_portfolios\` ADD CONSTRAINT \`FK_80af8491c40cb79d75d0d1f453d\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_subscriptions\` ADD CONSTRAINT \`FK_0641da02314913e28f6131310eb\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_subscriptions\` ADD CONSTRAINT \`FK_ec9362dd8ff98a317e9c66bcd6f\` FOREIGN KEY (\`package_id\`) REFERENCES \`subscription_packages\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`watchlists\` ADD CONSTRAINT \`FK_3e8bccad3dcd75fa977892c54bb\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`watchlists\` ADD CONSTRAINT \`FK_a44cd15737dd16fff31cdc44eba\` FOREIGN KEY (\`symbol_id\`) REFERENCES \`symbols\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`watchlists\` DROP FOREIGN KEY \`FK_a44cd15737dd16fff31cdc44eba\``);
        await queryRunner.query(`ALTER TABLE \`watchlists\` DROP FOREIGN KEY \`FK_3e8bccad3dcd75fa977892c54bb\``);
        await queryRunner.query(`ALTER TABLE \`user_subscriptions\` DROP FOREIGN KEY \`FK_ec9362dd8ff98a317e9c66bcd6f\``);
        await queryRunner.query(`ALTER TABLE \`user_subscriptions\` DROP FOREIGN KEY \`FK_0641da02314913e28f6131310eb\``);
        await queryRunner.query(`ALTER TABLE \`virtual_portfolios\` DROP FOREIGN KEY \`FK_80af8491c40cb79d75d0d1f453d\``);
        await queryRunner.query(`ALTER TABLE \`virtual_holdings\` DROP FOREIGN KEY \`FK_10e60e3392d30dec8df94b21ece\``);
        await queryRunner.query(`ALTER TABLE \`virtual_holdings\` DROP FOREIGN KEY \`FK_ff87ac76bc21a58c927d634a08d\``);
        await queryRunner.query(`ALTER TABLE \`virtual_transactions\` DROP FOREIGN KEY \`FK_553de9662a6a5e3dc999a1748e6\``);
        await queryRunner.query(`ALTER TABLE \`virtual_transactions\` DROP FOREIGN KEY \`FK_aab9123451c6a75958b42da41b7\``);
        await queryRunner.query(`ALTER TABLE \`audit_log\` DROP FOREIGN KEY \`FK_cb11bd5b662431ea0ac455a27d7\``);
        await queryRunner.query(`ALTER TABLE \`phone_verification_codes\` DROP FOREIGN KEY \`FK_0dbeb26c5cef6479baec0d78db4\``);
        await queryRunner.query(`ALTER TABLE \`password_reset_tokens\` DROP FOREIGN KEY \`FK_52ac39dd8a28730c63aeb428c9c\``);
        await queryRunner.query(`ALTER TABLE \`user_pii\` DROP FOREIGN KEY \`FK_e85a7597ec6d0d467e7a469c556\``);
        await queryRunner.query(`ALTER TABLE \`sessions\` DROP FOREIGN KEY \`FK_085d540d9f418cfbdc7bd55bb19\``);
        await queryRunner.query(`DROP INDEX \`IDX_80c717c53b6831e5f4fd84e840\` ON \`virtual_leaderboard\``);
        await queryRunner.query(`DROP INDEX \`IDX_d54ddd7d6b0ec56ffac255b177\` ON \`virtual_leaderboard\``);
        await queryRunner.query(`DROP TABLE \`virtual_leaderboard\``);
        await queryRunner.query(`DROP INDEX \`IDX_97e54cee8cbc1ec75de877e809\` ON \`watchlists\``);
        await queryRunner.query(`DROP INDEX \`IDX_3e8bccad3dcd75fa977892c54b\` ON \`watchlists\``);
        await queryRunner.query(`DROP INDEX \`IDX_a44cd15737dd16fff31cdc44eb\` ON \`watchlists\``);
        await queryRunner.query(`DROP TABLE \`watchlists\``);
        await queryRunner.query(`DROP INDEX \`IDX_4263ae397e23dff35b72ddfd34\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_cf427b0b12e1b2ee93a64328e1\` ON \`user_subscriptions\``);
        await queryRunner.query(`DROP INDEX \`IDX_409f50ec5f890102bbe16b02a9\` ON \`user_subscriptions\``);
        await queryRunner.query(`DROP TABLE \`user_subscriptions\``);
        await queryRunner.query(`DROP INDEX \`IDX_4d8bf52f924d05dfcbc7355ae9\` ON \`subscription_packages\``);
        await queryRunner.query(`DROP TABLE \`subscription_packages\``);
        await queryRunner.query(`DROP TABLE \`virtual_portfolios\``);
        await queryRunner.query(`DROP TABLE \`virtual_holdings\``);
        await queryRunner.query(`DROP INDEX \`IDX_8537c94ae17acdcbd2cc15c99a\` ON \`symbols\``);
        await queryRunner.query(`DROP TABLE \`symbols\``);
        await queryRunner.query(`DROP INDEX \`IDX_6ad3ee8d7b3e38a44d297dd7d9\` ON \`virtual_transactions\``);
        await queryRunner.query(`DROP INDEX \`IDX_02dbb30ab6376cd41e688dd7aa\` ON \`virtual_transactions\``);
        await queryRunner.query(`DROP TABLE \`virtual_transactions\``);
        await queryRunner.query(`DROP TABLE \`audit_log\``);
        await queryRunner.query(`DROP INDEX \`IDX_f0508fbd372dfe40db9160498f\` ON \`phone_verification_codes\``);
        await queryRunner.query(`DROP TABLE \`phone_verification_codes\``);
        await queryRunner.query(`DROP INDEX \`IDX_91185d86d5d7557b19abbb2868\` ON \`password_reset_tokens\``);
        await queryRunner.query(`DROP TABLE \`password_reset_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_aba7f426e9bb429ff282f18d6c\` ON \`user_pii\``);
        await queryRunner.query(`DROP TABLE \`user_pii\``);
        await queryRunner.query(`DROP TABLE \`sessions\``);
    }

}
